# Generated by Django 5.0.7 on 2024-07-14 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='место')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время')),
                ('periodicity', models.PositiveIntegerField(default=1, verbose_name='периодичность в днях')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('is_pleasurable', models.BooleanField(blank=True, default=False, null=True, verbose_name='приятная привычка')),
                ('reward', models.CharField(blank=True, null=True, verbose_name='вознаграждени')),
                ('lead_time', models.IntegerField(verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(blank=True, default=False, null=True, verbose_name='публичная привычка')),
                ('date_of_next_reminder_sending', models.DateField(blank=True, null=True, verbose_name='дата отправки следуюзего напоминания')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-time'],
            },
        ),
    ]
