# Generated by Django 5.0.7 on 2024-07-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_pleasurable',
            field=models.BooleanField(default=False, verbose_name='приятная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='публичная привычка'),
        ),
    ]
